version: "3.4"

services:
  back-end:
    container_name: back-end
    build:
      network: host
      context: ./back-end
    ports:
      - 8000:8000

  front-end:
    container_name: front-end
    depends_on:
      - back-end
    build:
      network: host
      context: ./front-end
    ports:
      - 3000:3000